INSERT INTO W0GBMA30_PROD.dbo.Prog_List (Fun_ID,FunName_TW,FunName_EN,FunName_CN,Enable,IsDB,[TYPE],SEQ,INSCTL,QRYCTL,SAECTL,DELCTL,EXPCTL,IMPCTL,CRTCTL,FT1CTL,FT2CTL,ICON,ROUTER) VALUES
	 (N'WC001',N'依物料盤點-日盤',N'Bin Box Cycle Count',N'Bin Box Cycle Count',N'Y',N'1',N'WC',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WC002',N'指定儲位區域物料盤點',N' ',N'',N'Y',N'1',N'WC',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WC003',N'盤點調帳',N'Cycle Adjustment Setting',N'Cycle Adjustment Setting',N'Y',N'1',N'WC',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM001',N'儲位地標設定',N' ',N'',N'Y',N'1',N'WM',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM002',N'代碼資料維護',N' ',N'',N'Y',N'1',N'WM',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM003',N'命令資料維護',N' ',N' ',N'Y',N'1',N'WM',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM004',N'物料資料維護',N' ',N' ',N'Y',N'1',N'WM',4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM005',N'單據資料維護',N' ',N' ',N'Y',N'1',N'WM',5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM006',N'儲位資料維護',N' ',N' ',N'Y',N'1',N'WM',6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM007',N'使用者資料維護',N' ',N' ',N'Y',N'1',N'WM',7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO W0GBMA30_PROD.dbo.Prog_List (Fun_ID,FunName_TW,FunName_EN,FunName_CN,Enable,IsDB,[TYPE],SEQ,INSCTL,QRYCTL,SAECTL,DELCTL,EXPCTL,IMPCTL,CRTCTL,FT1CTL,FT2CTL,ICON,ROUTER) VALUES
	 (N'WM008',N'權限資料維護',N'',N'',N'Y',N'1',N'WM',8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM009',N'群組定義維護',N'',N'',N'Y',N'1',N'WM',9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM010',N'多語系維護',N'',N'',N'Y',N'1',N'WM',10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM011',N'模式切換功能',N'',N'',N'Y',N'1',N'WM',11,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM012',N'載具資料維護',N'',N'',N'Y',N'1',N'WM',12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM013',N'物料類別維護',N'',N'',N'Y',N'1',N'WM',13,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM014',N'印表機維護',N'',N'',N'Y',N'1',N'WM',14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM015',N'標簽列印',N'',N'',N'Y',N'1',N'WM',15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM016',N'站口維護',N'',N'',N'Y',N'1',N'WM',16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WM017',N'API重送',N'',N'',N'Y',N'1',N'WM',17,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO W0GBMA30_PROD.dbo.Prog_List (Fun_ID,FunName_TW,FunName_EN,FunName_CN,Enable,IsDB,[TYPE],SEQ,INSCTL,QRYCTL,SAECTL,DELCTL,EXPCTL,IMPCTL,CRTCTL,FT1CTL,FT2CTL,ICON,ROUTER) VALUES
	 (N'WM019',N'過期料維護',N'',N'',N'Y',N'1',N'WM',19,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP001',N'Call Off Process',N' ',N' ',N'Y',N'1',N'WP',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP002',N'空棧板入出庫作業',N' ',N' ',N'Y',N'1',N'WP',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP003',N'L10 Pre-assembly Store in',N' ',N' ',N'Y',N'1',N'WP',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP004',N'無單出庫作業',N' ',N' ',N'Y',N'1',N'WP',4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP005',N'指定物料出庫作業',N' ',N' ',N'Y',N'1',N'WP',5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP006',N'長桿件單據入庫作業',N' ',N' ',N'Y',N'1',N'WP',6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP007',N'單據轉出Purege作業',N' ',N' ',N'Y',N'1',N'WP',7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP008',N'單據轉發出庫作業',N' ',N' ',N'Y',N'1',N'WP',8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP009',N'工作站命令查詢及撿料/盤點作業指示',N' ',N' ',N'Y',N'1',N'WP',9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO W0GBMA30_PROD.dbo.Prog_List (Fun_ID,FunName_TW,FunName_EN,FunName_CN,Enable,IsDB,[TYPE],SEQ,INSCTL,QRYCTL,SAECTL,DELCTL,EXPCTL,IMPCTL,CRTCTL,FT1CTL,FT2CTL,ICON,ROUTER) VALUES
	 (N'WP010',N'DN RM 出庫作業',N' ',N' ',N'Y',N'1',N'WP',10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP011',N'DN 換貨',N'',N'',N'Y',N'1',N'WP',11,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP021',N'庫對庫作業',N' ',N' ',N'Y',N'1',N'WP',21,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WP022',N'站對站作業',N' ',N' ',N'Y',N'1',N'WP',22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ001',N'儲位資料查詢',N' ',N' ',N'Y',N'1',N'WQ',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ002',N'儲位狀態查詢',N' ',N' ',N'Y',N'1',N'WQ',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ003',N'工作站命令查詢',N' ',N' ',N'Y',N'1',N'WQ',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ004',N'庫存資料查詢',N' ',N' ',N'Y',N'1',N'WQ',4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ005',N'命令資料查詢',N' ',N' ',N'Y',N'1',N'WQ',5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ006',N'異動資料查詢',N' ',N' ',N'N',N'1',N'WQ',6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO W0GBMA30_PROD.dbo.Prog_List (Fun_ID,FunName_TW,FunName_EN,FunName_CN,Enable,IsDB,[TYPE],SEQ,INSCTL,QRYCTL,SAECTL,DELCTL,EXPCTL,IMPCTL,CRTCTL,FT1CTL,FT2CTL,ICON,ROUTER) VALUES
	 (N'WQ007',N'盤點資料查詢',N' ',N' ',N'N',N'1',N'WQ',7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ008',N'單據資料查詢',N' ',N' ',N'Y',N'1',N'WQ',8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ009',N'物料資料查詢',N' ',N' ',N'Y',N'1',N'WQ',9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ010',N'GR 收料查詢',N'',N'',N'Y',N'1',N'WQ',10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ011',N'Return 收料查詢',N'',N'',N'Y',N'1',N'WQ',11,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ012',N'載具資料查詢',N'',N'',N'Y',N'1',N'WQ',12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ013',N'載具搬運履歷查詢',N'',N'',N'Y',N'1',N'WQ',13,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ014',N'儲位地標查詢',N'',N'',N'Y',N'1',N'WQ',14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ015',N'L10 Pre-assembly store-in',N'',N'',N'Y',N'1',N'WQ',15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ017',N'Command History Query',N'',N'',N'Y',N'1',N'WQ',17,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO W0GBMA30_PROD.dbo.Prog_List (Fun_ID,FunName_TW,FunName_EN,FunName_CN,Enable,IsDB,[TYPE],SEQ,INSCTL,QRYCTL,SAECTL,DELCTL,EXPCTL,IMPCTL,CRTCTL,FT1CTL,FT2CTL,ICON,ROUTER) VALUES
	 (N'WQ018',N'歷史資料查詢',N' ',N'',N'Y',N'1',N'WQ',18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ019',N'設備異常報表查詢',N'',N'',N'Y',N'1',N'WQ',19,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 (N'WQ020',N'L10\L11缺料查詢查詢',N'',N'',N'Y',N'1',N'WQ',20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
